[build]
  command = "npm run build"
  functions = "netlify/functions"
  publish = "out"

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200

[context.production]
  environment = { NODE_ENV = "production" }

[context.preview]
  environment = { NODE_ENV = "preview" }

[context.deploy-preview]
  environment = { NODE_ENV = "preview" }

[context.branch-deploy]
  environment = { NODE_ENV = "preview" }
