// MORTGAGE SERVICER LOSS-MITIGATION CONTACTS
// ---------------------------------------------------------------------------
// Every phone number here was read on the servicer's OWN website (the page is
// recorded in verifiedFrom) on 2026-09-30. Verified-or-null: a null phone
// means the servicer's own pages could not be read to confirm one, not that
// it lacks one. NEVER fill a null from a third-party site, a directory or
// memory; re-verify on the servicer's own domain or leave it null.
//
// phoneType 'loss-mitigation' = published specifically for hardship or
// mortgage assistance; 'general' = main servicing line (ask for loss
// mitigation). options lists only assistance options the servicer's own page
// names. Each servicer gets a page at /servicers/<slug>/.
// ---------------------------------------------------------------------------

export interface ServicerLine {
  label: string;
  phone: string;
}

export interface Servicer {
  slug: string;
  name: string;
  /** Other names people search or see on statements. */
  aliases: string[];
  assistUrl: string | null;
  phone: string | null;
  phoneType: 'loss-mitigation' | 'general' | null;
  /** Overrides the default phone label when the number belongs to someone else. */
  phoneLabel?: string;
  hours: string | null;
  onlineApp: boolean | null;
  options: string[];
  parent?: string;
  /** Manages loans for other lenders; statements may carry another name. */
  subservicer?: boolean;
  otherLines?: ServicerLine[];
  note?: string;
  verifiedFrom: string | null;
}

export const SERVICERS: Servicer[] = [
  {
    slug: "mr-cooper",
    name: "Mr. Cooper",
    aliases: ["Nationstar", "Nationstar Mortgage", "Mr. Cooper Powered by Rocket Mortgage"],
    assistUrl: "https://www.rocketmortgage.com/legal/mortgage-assistance",
    phone: "866-316-2432",
    phoneType: "loss-mitigation",
    hours: null,
    onlineApp: null,
    options: ["Repayment plan", "Loan modification"],
    parent: "Rocket Mortgage",
    otherLines: [
      { label: "Rocket Mortgage existing-client line", phone: "800-476-2538" },
    ],
    note: "Mr. Cooper has joined Rocket Mortgage. mrcooper.com is retired and your loan is now managed through Rocket Mortgage with the same loan number and terms. Mr. Cooper was known as Nationstar Mortgage before 2017.",
    verifiedFrom: "https://www.rocketmortgage.com/legal/mortgage-assistance",
  },
  {
    slug: "rocket-mortgage",
    name: "Rocket Mortgage",
    aliases: ["Rocket", "Rocket.com"],
    assistUrl: "https://www.rocketmortgage.com/legal/mortgage-assistance",
    phone: "866-316-2432",
    phoneType: "loss-mitigation",
    hours: null,
    onlineApp: null,
    options: ["Repayment plan", "Loan modification"],
    otherLines: [
      { label: "Existing-client line", phone: "800-476-2538" },
    ],
    note: "Rocket asks you to call to speak with a team member about assistance. Former Mr. Cooper loans are now serviced by Rocket.",
    verifiedFrom: "https://www.rocketmortgage.com/legal/mortgage-assistance",
  },
  {
    slug: "wells-fargo",
    name: "Wells Fargo Home Mortgage",
    aliases: [],
    assistUrl: "https://www.wellsfargo.com/mortgage/manage-account/payment-help/",
    phone: "800-678-7986",
    phoneType: "loss-mitigation",
    hours: null,
    onlineApp: false,
    options: ["Forbearance", "Repayment plan", "Loan modification", "Short sale", "Deed in lieu of foreclosure"],
    otherLines: [
      { label: "General mortgage customer service", phone: "866-234-8271" },
    ],
    note: "The assistance application is a PDF you sign and send back (all pages). If you already applied, sign on to check status or upload documents.",
    verifiedFrom: "https://www.wellsfargo.com/mortgage/manage-account/payment-help/",
  },
  {
    slug: "chase",
    name: "Chase Home Lending",
    aliases: ["Chase Mortgage"],
    assistUrl: "https://www.chase.com/personal/mortgage/mortgage-assistance",
    phone: "800-848-9380",
    phoneType: "loss-mitigation",
    hours: null,
    onlineApp: true,
    options: ["Forbearance", "Repayment plan", "Loan modification", "Reinstatement", "Short sale", "Deed in lieu of foreclosure"],
    otherLines: [
      { label: "Questions about gathering documents", phone: "866-550-5705" },
    ],
    note: "You complete Chase's Request for Mortgage Assistance form and upload it through your chase.com home lending account. Chase says a Relationship Manager contacts you within 30 days.",
    verifiedFrom: "https://www.chase.com/personal/mortgage/mortgage-assistance/get-started",
  },
  {
    slug: "bank-of-america",
    name: "Bank of America Home Loans",
    aliases: ["BofA", "BoA"],
    assistUrl: "https://homeloanhelp.bankofamerica.com/",
    phone: "800-669-6650",
    phoneType: "loss-mitigation",
    hours: "Mon-Fri 8am-8pm ET",
    onlineApp: null,
    options: ["Forbearance", "Loan modification", "Short sale", "Deed in lieu of foreclosure"],
    otherLines: [
      { label: "General existing-mortgage line", phone: "800-669-6607" },
    ],
    note: "Help is available in English, Spanish and other languages.",
    verifiedFrom: "https://homeloanhelp.bankofamerica.com/",
  },
  {
    slug: "freedom-mortgage",
    name: "Freedom Mortgage",
    aliases: ["Freedom"],
    assistUrl: "https://www.freedommortgage.com/help-with-mortgage-payments",
    phone: "855-690-5900",
    phoneType: "loss-mitigation",
    hours: "Mon-Fri 8am-8pm ET; Sat 9am-2pm ET",
    onlineApp: null,
    options: ["Forbearance", "Repayment plan", "Loan modification", "Short sale", "Deed in lieu of foreclosure"],
    note: "You start by logging in; the Hardship Assistance Request form is under Help Center > Forms in your online account. Freedom also lists LossMitigation@FreedomMortgage.com.",
    verifiedFrom: "https://www.freedommortgage.com/help-with-mortgage-payments",
  },
  {
    slug: "pennymac",
    name: "Pennymac",
    aliases: ["PennyMac Loan Services"],
    assistUrl: "https://www.pennymac.com/relief-and-assistance",
    phone: "866-545-9070",
    phoneType: "loss-mitigation",
    hours: null,
    onlineApp: null,
    options: ["Loan modification", "Short sale", "Deed in lieu of foreclosure"],
    otherLines: [
      { label: "General customer support", phone: "800-777-4001" },
    ],
    verifiedFrom: "https://www.pennymac.com/relief-and-assistance",
  },
  {
    slug: "newrez",
    name: "Newrez",
    aliases: ["New Residential"],
    assistUrl: "https://www.newrez.com/loss-mitigation/",
    phone: "888-673-5521",
    phoneType: "general",
    hours: null,
    onlineApp: true,
    options: ["Forbearance", "Repayment plan", "Loan modification", "Short sale", "Deed in lieu of foreclosure"],
    otherLines: [
      { label: "Customer service (listed in Newrez help articles)", phone: "866-317-2347" },
    ],
    note: "The Start an Application link on the loss mitigation page requires signing in to your Newrez account.",
    verifiedFrom: "https://www.newrez.com/loss-mitigation/",
  },
  {
    slug: "sps",
    name: "Select Portfolio Servicing (SPS)",
    aliases: ["SPS", "Select Portfolio"],
    assistUrl: "https://www.spservicing.com/StaticDetails/RequestAssistance",
    phone: "888-818-6032",
    phoneType: "loss-mitigation",
    hours: null,
    onlineApp: true,
    options: ["Repayment plan", "Loan modification", "Payment deferral", "Short sale", "Deed in lieu of foreclosure"],
    otherLines: [
      { label: "General customer service", phone: "800-258-8602" },
    ],
    note: "Log in and complete the online Request for Mortgage Assistance under the Assistance Programs menu.",
    verifiedFrom: "https://www.spservicing.com/StaticDetails/RequestAssistance",
  },
  {
    slug: "phh-onity",
    name: "Onity Mortgage (formerly PHH)",
    aliases: ["PHH", "PHH Mortgage", "Onity", "MortgageQuestions.com"],
    assistUrl: "https://www.mortgagequestions.com/Assistance",
    phone: "800-449-8767",
    phoneType: "general",
    hours: "Mon-Fri 8am-9pm ET; Sat 8am-5pm ET",
    onlineApp: true,
    options: ["Forbearance", "Repayment plan", "Loan modification", "Short sale", "Deed in lieu of foreclosure"],
    note: "PHH Mortgage is now Onity Mortgage Corporation. To apply, log in, go to Payments, then Payment Assistance, and select Request Assistance; you can also download the application or apply by phone.",
    verifiedFrom: "https://www.mortgagequestions.com/Assistance",
  },
  {
    slug: "carrington",
    name: "Carrington Mortgage Services",
    aliases: ["Carrington"],
    assistUrl: "https://www.carringtonmortgage.com/mortgage-assistance",
    phone: "800-561-4567",
    phoneType: "general",
    hours: "Mon-Fri 8am-8pm ET",
    onlineApp: true,
    options: ["Forbearance", "Repayment plan", "Loan modification", "Short sale", "Deed in lieu of foreclosure"],
    note: "Log in and open the Mortgage Assistance Portal to upload documents. FHA borrowers can answer employment and income questions online or by phone; other loan types need a full application with documents.",
    verifiedFrom: "https://www.carringtonmortgage.com/mortgage-assistance",
  },
  {
    slug: "mt-bank",
    name: "M&T Bank",
    aliases: ["M&T", "M and T Bank"],
    assistUrl: "https://www.mtb.com/personal/mortgages-and-loans/mortgages/manage/paying/assistance",
    phone: "800-724-1633",
    phoneType: "loss-mitigation",
    hours: null,
    onlineApp: true,
    options: ["Forbearance", "Repayment plan", "Loan modification", "Partial claim (FHA)", "Short sale", "Deed in lieu of foreclosure"],
    note: "Apply in M&T Online Banking (select the mortgage, then Account Management > Request Assistance), or download the form for your loan type and email, fax or mail it.",
    verifiedFrom: "https://www.mtb.com/personal/mortgages-and-loans/mortgages/manage/paying/assistance",
  },
  {
    slug: "uwm",
    name: "United Wholesale Mortgage (UWM)",
    aliases: ["UWM"],
    assistUrl: "https://www.uwm.com/loan-servicing",
    phone: "888-896-9658",
    phoneType: "general",
    hours: "24/7",
    onlineApp: null,
    options: [],
    note: "UWM publishes a 24/7 servicing line and a Help for Homeowners resource page but does not list specific assistance options on its site.",
    verifiedFrom: "https://www.uwm.com/loan-servicing",
  },
  {
    slug: "cenlar",
    name: "Cenlar",
    aliases: ["Cenlar FSB", "LoanAdministration.com"],
    assistUrl: "https://www.cenlar.com/homeowners/homeowners-resources",
    phone: "800-223-6527",
    phoneType: "general",
    hours: null,
    onlineApp: null,
    options: [],
    subservicer: true,
    note: "Cenlar, based in Ewing, NJ, is a subservicer: it manages loans for many banks and credit unions, so your statement may show another lender's name. Homeowners manage these loans at loanadministration.com; use the number printed on your statement.",
    verifiedFrom: "https://www.cenlar.com/contact",
  },
  {
    slug: "loancare",
    name: "LoanCare",
    aliases: ["LoanCare Servicing", "MyLoanCare"],
    assistUrl: "https://myloancare.com/mortgage-assistance/financial-assistance",
    phone: null,
    phoneType: null,
    hours: null,
    onlineApp: null,
    options: [],
    parent: "Fidelity National Financial",
    subservicer: true,
    note: "LoanCare is a subservicer for many lenders, including NJHMFA first mortgages and some Lakeview loans. We could not read a phone number on LoanCare's own site, so use the number on your statement or the assistance portal.",
    verifiedFrom: null,
  },
  {
    slug: "pnc",
    name: "PNC Bank",
    aliases: ["PNC", "PNC Mortgage"],
    assistUrl: "https://www.pnc.com/en/customer-service/mortgage-customer-service/financial-trouble.html",
    phone: "800-523-8654",
    phoneType: "loss-mitigation",
    hours: "Mon-Thu 8am-9pm ET; Fri 8am-7pm ET; Sat 8am-2pm ET",
    onlineApp: true,
    options: ["Forbearance", "Repayment plan", "Loan modification", "Payment deferral", "Reinstatement", "Short sale", "Deed in lieu of foreclosure"],
    otherLines: [
      { label: "Home equity hardship", phone: "866-622-2657" },
    ],
    note: "PNC's digital hardship application at hardship.pnc.com requires your PNC online banking sign-in. You can also download the application and mail, fax or email it.",
    verifiedFrom: "https://www.pnc.com/en/customer-service/mortgage-customer-service/financial-trouble.html",
  },
  {
    slug: "us-bank",
    name: "U.S. Bank",
    aliases: ["US Bank", "U.S. Bank Home Mortgage", "USBank"],
    assistUrl: "https://www.usbank.com/home-loans/mortgage/mortgage-assistance.html",
    phone: "855-698-7627",
    phoneType: "loss-mitigation",
    hours: "Mon-Fri 7am-8pm CT; Sat 8am-2pm CT",
    onlineApp: true,
    options: ["Short sale", "Deed in lieu of foreclosure"],
    otherLines: [
      { label: "Default Counseling (for past-due payments)", phone: "800-365-7900" },
    ],
    note: "Apply by logging in to online banking, selecting the mortgage, then Mortgage assistance.",
    verifiedFrom: "https://www.usbank.com/home-loans/mortgage/mortgage-assistance.html",
  },
  {
    slug: "truist",
    name: "Truist",
    aliases: ["Truist Mortgage"],
    assistUrl: "https://www.truist.com/mortgage/manage-your-mortgage/mortgage-assistance",
    phone: "800-443-1032",
    phoneType: "loss-mitigation",
    hours: "Mon-Thu 8am-10pm ET; Fri 8am-8pm ET; Sat 9am-1pm ET",
    onlineApp: false,
    options: ["Repayment plan", "Loan modification"],
    note: "Truist asks you to call first, then send documents by fax, mail or email. It says a Home Preservation Specialist reviews a complete application within 30 days.",
    verifiedFrom: "https://www.truist.com/mortgage/manage-your-mortgage/mortgage-assistance",
  },
  {
    slug: "td-bank",
    name: "TD Bank",
    aliases: ["TD", "TD Bank N.A."],
    assistUrl: "https://www.td.com/us/en/personal-banking/learning/collections-information",
    phone: "800-742-2651",
    phoneType: "loss-mitigation",
    hours: "Mon-Fri 8am-9pm ET; Sat 8am-5pm ET",
    onlineApp: false,
    options: ["Repayment plan", "Loan modification", "Short sale", "Deed in lieu of foreclosure"],
    note: "TD asks you to complete its Request for Assistance form, call a loan assistance representative, then submit the form with income documents.",
    verifiedFrom: "https://www.td.com/us/en/personal-banking/learning/collections-information",
  },
  {
    slug: "citizens",
    name: "Citizens",
    aliases: ["Citizens Bank"],
    assistUrl: "https://www.citizensbank.com/loans/mortgage-trouble-making-payments.aspx",
    phone: "800-456-8855",
    phoneType: "loss-mitigation",
    hours: "Mon-Fri 8am-8pm ET",
    onlineApp: true,
    options: ["Forbearance", "Repayment plan", "Loan modification", "Payment deferral", "Short sale", "Deed in lieu of foreclosure"],
    note: "Citizens' online Loan Solution Center has you register with your loan number, answer a questionnaire and upload forms. Mail and fax to the Loss Mitigation department are also accepted.",
    verifiedFrom: "https://www.citizensbank.com/loans/mortgage-trouble-making-payments.aspx",
  },
  {
    slug: "santander",
    name: "Santander Bank",
    aliases: ["Santander"],
    assistUrl: "https://www.santanderbank.com/personal/resources/mortgages/financial-hardship-mortgage-assistance-options",
    phone: "855-241-5699",
    phoneType: "loss-mitigation",
    hours: null,
    onlineApp: null,
    options: ["Forbearance", "Repayment plan", "Loan modification", "Short sale", "Deed in lieu of foreclosure"],
    note: "Santander directs borrowers to call a Customer Service Center Advisor and does not describe an online application.",
    verifiedFrom: "https://www.santanderbank.com/personal/resources/mortgages/financial-hardship-mortgage-assistance-options",
  },
  {
    slug: "valley-bank",
    name: "Valley Bank",
    aliases: ["Valley National Bank", "Valley"],
    assistUrl: "https://www.valley.com/customer-care/mortgage-help",
    phone: "800-522-4100",
    phoneType: "general",
    phoneLabel: "Bank-wide customer service (24/7)",
    hours: "24/7",
    onlineApp: null,
    options: [],
    note: "This is Valley's bank-wide line, not a mortgage-specific number; ask for mortgage assistance or loss mitigation. Valley's mortgage help pages could not be read to confirm a direct hardship line.",
    verifiedFrom: "https://www.valley.com/customer-care",
  },
  {
    slug: "provident-bank",
    name: "Provident Bank",
    aliases: ["Provident", "Provident Bank NJ"],
    assistUrl: "https://www.provident.bank/personal-services/home-loans/mortgage-login",
    phone: "800-448-7768",
    phoneType: "general",
    phoneLabel: "Bank-wide customer service",
    hours: "Mon-Fri 8am-7pm; Sat 9am-2pm",
    onlineApp: null,
    options: [],
    note: "This is Provident's bank-wide line. Provident's mortgage login goes to an outside servicing website, so check your statement for the company that actually services your loan.",
    verifiedFrom: "https://www.provident.bank/contact-us",
  },
  {
    slug: "columbia-bank",
    name: "Columbia Bank",
    aliases: ["Columbia Bank NJ"],
    assistUrl: "https://www.columbiabankonline.com/mortgage-assistance",
    phone: "800-522-4167",
    phoneType: "general",
    hours: null,
    onlineApp: true,
    options: [],
    note: "Columbia's mortgage assistance page is an online request form; a representative contacts you after you submit it.",
    verifiedFrom: "https://www.columbiabankonline.com/mortgage-assistance",
  },
  {
    slug: "huntington",
    name: "Huntington Bank",
    aliases: ["Huntington", "Huntington National Bank"],
    assistUrl: "https://www.huntington.com/Personal/mortgage-education-tools/payment-help",
    phone: "800-323-9865",
    phoneType: "loss-mitigation",
    hours: "Mon-Fri 8am-9pm ET; Sat 8am-1pm ET",
    onlineApp: false,
    options: ["Forbearance", "Repayment plan", "Loan modification", "Payment deferral", "Partial claim (FHA)", "Short sale", "Deed in lieu of foreclosure"],
    note: "Huntington's loss mitigation forms (Fannie Mae, Freddie Mac, FHA or USDA versions) go to its Home Savers Department by mail, fax or email.",
    verifiedFrom: "https://www.huntington.com/Personal/mortgage-education-tools/payment-help",
  },
  {
    slug: "keybank",
    name: "KeyBank",
    aliases: ["Key Bank", "Key"],
    assistUrl: "https://www.key.com/personal/loans-lines/homeowner-hardship-relief.html",
    phone: "866-947-2610",
    phoneType: "loss-mitigation",
    hours: "Mon-Thu 8am-7pm ET; Fri 8am-5pm ET",
    onlineApp: true,
    options: ["Forbearance", "Repayment plan", "Loan modification", "Payment deferral", "Short sale", "Deed in lieu of foreclosure"],
    note: "The online assistance form requires signing in to KeyBank online banking.",
    verifiedFrom: "https://www.key.com/personal/loans-lines/homeowner-hardship-relief.html",
  },
  {
    slug: "loandepot",
    name: "loanDepot",
    aliases: ["loan Depot"],
    assistUrl: "https://www.loandepot.com/about/loan-servicing/support-resources",
    phone: "866-258-6572",
    phoneType: "general",
    hours: null,
    onlineApp: false,
    options: ["Forbearance", "Repayment plan", "Loan modification", "Partial claim (FHA)", "Short sale", "Deed in lieu of foreclosure"],
    note: "You complete loanDepot's Borrower Response Package (a PDF) and return it; the number is the existing-loans servicing line.",
    verifiedFrom: "https://www.loandepot.com/about/loan-servicing/support-resources",
  },
  {
    slug: "guild-mortgage",
    name: "Guild Mortgage",
    aliases: ["Guild"],
    assistUrl: "https://www.guildmortgage.com/help-center/hardship-assistance/",
    phone: "800-365-4884",
    phoneType: "loss-mitigation",
    hours: "Mon-Fri 5am-5pm PT",
    onlineApp: true,
    options: ["Forbearance", "Repayment plan", "Loan modification", "Payment deferral", "Partial claim (FHA)", "Short sale", "Deed in lieu of foreclosure"],
    note: "Apply online by logging in to your Guild account, or email hardshipassistance@guildmortgage.com. Guild notes that available options depend on who owns your loan.",
    verifiedFrom: "https://www.guildmortgage.com/help-center/hardship-assistance/",
  },
  {
    slug: "lakeview",
    name: "Lakeview Loan Servicing",
    aliases: ["Lakeview"],
    assistUrl: "https://lakeview.com/questions/",
    phone: "855-294-8564",
    phoneType: "general",
    hours: "Mon-Thu 8am-9pm ET; Fri 8am-8pm ET; Sat 10am-2pm ET",
    onlineApp: null,
    options: [],
    subservicer: true,
    otherLines: [
      { label: "LoanCare (Lakeview subservicer)", phone: "800-509-0183" },
      { label: "M&T Bank (Lakeview subservicer)", phone: "800-724-2224" },
      { label: "ServiceMac (Lakeview subservicer)", phone: "844-478-2622" },
      { label: "Carrington (Lakeview subservicer)", phone: "855-218-3690" },
      { label: "Champion (Lakeview subservicer)", phone: "833-685-2580" },
    ],
    note: "Lakeview owns the servicing rights but partners with subservicers (LoanCare, M&T Bank, ServiceMac, Carrington, Champion), so your statement may show one of those names. Call the company named on your statement about assistance.",
    verifiedFrom: "https://lakeview.com/questions/",
  },
  {
    slug: "planet-home-lending",
    name: "Planet Home Lending",
    aliases: ["Planet", "Planet Home"],
    assistUrl: "https://www.planethomelending.com/homeowners-assistance",
    phone: "866-882-8187",
    phoneType: "general",
    hours: "Mon-Fri 8:30am-9pm ET",
    onlineApp: true,
    options: ["Forbearance", "Repayment plan", "Loan modification", "Short sale", "Deed in lieu of foreclosure"],
    note: "Use the servicing number, not the new-loans number shown on the assistance page. Applications can be uploaded at loansolutioncenter.com or emailed to mitigation@planethomelending.com.",
    verifiedFrom: "https://www.planethomelending.com/contact",
  },
  {
    slug: "midland-mortgage",
    name: "Midland Mortgage",
    aliases: ["MidFirst Bank", "Midland", "MidFirst"],
    assistUrl: "https://www.mymidlandmortgage.com/mortgage-assistance",
    phone: "405-767-5815",
    phoneType: "loss-mitigation",
    hours: null,
    onlineApp: null,
    options: ["Forbearance", "Repayment plan", "Loan modification", "Partial claim (FHA)", "Short sale", "Deed in lieu of foreclosure"],
    parent: "MidFirst Bank",
    otherLines: [
      { label: "Delinquency Assistance Center (listed on MidFirst Bank's site)", phone: "800-552-3000" },
    ],
    note: "Midland is a division of MidFirst Bank. You pick the assistance form for your loan type (FHA, VA, USDA or conventional) or sign in to get the right one.",
    verifiedFrom: "https://www.mymidlandmortgage.com/contact",
  },
  {
    slug: "rushmore",
    name: "Rushmore Servicing",
    aliases: ["Rushmore"],
    assistUrl: "https://www.rushmoreservicing.com/help-center/mortgage-assistance",
    phone: "877-888-4606",
    phoneType: "general",
    hours: "Mon-Fri 7am-8pm CT",
    onlineApp: true,
    options: ["Repayment plan", "Loan modification", "Payment deferral", "Short sale", "Deed in lieu of foreclosure"],
    note: "You can complete Rushmore's mortgage assistance application online or download it to mail or fax. Rushmore's sign-in now points to a Mr. Cooper account.",
    verifiedFrom: "https://www.rushmoreservicing.com/contact_us",
  },
  {
    slug: "fay-servicing",
    name: "Fay Servicing",
    aliases: ["Fay"],
    assistUrl: "https://www.fayservicing.com/get-help",
    phone: "800-495-7166",
    phoneType: "general",
    hours: "Mon-Thu 9am-8pm ET; Fri 9am-6pm ET; Sat 10am-1pm ET",
    onlineApp: null,
    options: [],
    note: "Fay uses one main number for general questions, payments and mortgage assistance; the application forms are on its Get Help page.",
    verifiedFrom: "https://www.fayservicing.com/contact-us",
  },
  {
    slug: "bsi-financial",
    name: "BSI Financial Services",
    aliases: ["BSI", "Servis One"],
    assistUrl: "https://www.bsifinancial.com/borrower_hardship_assistance.html",
    phone: "800-327-7861",
    phoneType: "loss-mitigation",
    hours: null,
    onlineApp: false,
    options: [],
    note: "BSI's legal name is Servis One, Inc. The Loss Mitigation Application is downloaded and mailed or faxed to its Default Resolution Team.",
    verifiedFrom: "https://www.bsifinancial.com/borrower_hardship_assistance.html",
  },
  {
    slug: "selene-finance",
    name: "Selene Finance",
    aliases: ["Selene"],
    assistUrl: "https://www.selenefinance.com/customer-assistance",
    phone: "877-735-3637",
    phoneType: "loss-mitigation",
    hours: null,
    onlineApp: false,
    options: ["Forbearance", "Repayment plan", "Loan modification", "Payment deferral", "Partial claim (FHA)", "Short sale", "Deed in lieu of foreclosure"],
    note: "Selene's Borrower Assistance Form packet is sent back by email, mail or fax.",
    verifiedFrom: "https://www.selenefinance.com/customer-assistance",
  },
  {
    slug: "shellpoint",
    name: "Shellpoint Mortgage Servicing",
    aliases: ["Shellpoint", "Newrez LLC dba Shellpoint Mortgage Servicing"],
    assistUrl: "https://www.shellpointmtg.com/helpful-tips/mortgage-help/",
    phone: "800-365-7107",
    phoneType: "general",
    hours: "Mon-Fri 8am-9pm ET; Sat 10am-2pm ET",
    onlineApp: null,
    options: ["Forbearance", "Repayment plan", "Loan modification"],
    parent: "Newrez LLC",
    note: "Shellpoint is a brand of Newrez LLC. It does not publish a separate loss mitigation line, so call customer care and ask for mortgage assistance.",
    verifiedFrom: "https://www.shellpointmtg.com/contact-us",
  },
  {
    slug: "sls",
    name: "Specialized Loan Servicing (SLS)",
    aliases: ["SLS", "Specialized Loan Servicing LLC"],
    assistUrl: "https://www.sls.net/get-help/covid-19",
    phone: "800-315-4757",
    phoneType: "general",
    hours: null,
    onlineApp: null,
    options: ["Forbearance", "Repayment plan", "Loan modification", "Payment deferral", "Partial claim (FHA)", "Reinstatement"],
    note: "Most of SLS's site could not be read; this number comes from its COVID-19 assistance page, which tells you to log in to your SLS account to request help. Confirm against your statement.",
    verifiedFrom: "https://www.sls.net/get-help/covid-19",
  },
  {
    slug: "flagstar",
    name: "Flagstar Bank",
    aliases: ["Flagstar"],
    assistUrl: "https://www.flagstar.com/personal/help/home-loans-support.html",
    phone: "800-968-7700",
    phoneType: "general",
    hours: null,
    onlineApp: null,
    options: [],
    note: "This is Flagstar's line for existing loans. Its hardship pages could not be read to confirm a direct hardship number or options.",
    verifiedFrom: "https://www.flagstar.com/personal/help/home-loans-support.html",
  },
  {
    slug: "njhmfa",
    name: "NJ Housing and Mortgage Finance Agency (NJHMFA)",
    aliases: ["NJHMFA", "HMFA", "New Jersey HMFA", "NJ Housing"],
    assistUrl: "https://nj.gov/dca/hmfa/homeowners/resources/",
    phone: "800-274-6600",
    phoneType: "general",
    phoneLabel: "LoanCare, which services NJHMFA first mortgages (as listed by NJHMFA)",
    hours: null,
    onlineApp: null,
    options: [],
    otherLines: [
      { label: "NJHMFA Servicing (second mortgages and down payment assistance loans)", phone: "800-654-6873" },
    ],
    note: "NJHMFA says its first mortgages are serviced by LoanCare and its second mortgages and down payment assistance loans by NJHMFA Servicing. NJ's ERMA program is no longer accepting applications.",
    verifiedFrom: "https://www.nj.gov/dca/hmfa/about/contactus/",
  },
  {
    slug: "amerihome",
    name: "AmeriHome Mortgage",
    aliases: ["AmeriHome"],
    assistUrl: "https://www.amerihome.com/resources/",
    phone: "888-469-0810",
    phoneType: "general",
    hours: "Mon-Fri 8am-5pm PT",
    onlineApp: null,
    options: [],
    note: "The number is AmeriHome's customer service line for existing accounts; its site lists no hardship options.",
    verifiedFrom: "https://www.amerihome.com/resources/",
  },
  {
    slug: "village-capital",
    name: "Village Capital & Investment",
    aliases: ["Village Capital"],
    assistUrl: "https://villagecapital.com/resources/borrower-assistance-for-homeowners/",
    phone: "800-919-0068",
    phoneType: "loss-mitigation",
    hours: "Mon-Fri 5am-7pm PT",
    onlineApp: null,
    options: ["Forbearance", "Repayment plan", "Loan modification", "Short sale", "Deed in lieu of foreclosure"],
    otherLines: [
      { label: "Main company line", phone: "800-619-0823" },
    ],
    note: "Village Capital asks borrowers to call its Customer Care Counselors and lists lossmit@villagecapital.com.",
    verifiedFrom: "https://villagecapital.com/resources/borrower-assistance-for-homeowners/",
  },
  {
    slug: "rate",
    name: "Rate (Guaranteed Rate)",
    aliases: ["Guaranteed Rate", "Rate.com"],
    assistUrl: "https://www.rate.com/servicing",
    phone: "866-934-7283",
    phoneType: "general",
    hours: "Mon-Fri 8:30am-5:30pm CT",
    onlineApp: null,
    options: [],
    note: "Rate sends hardship requests to a ServiceMac assistance portal, so your loan may be subserviced by ServiceMac.",
    verifiedFrom: "https://www.rate.com/mortgage/resource/contact-rate-customer-service",
  },
  {
    slug: "servicemac",
    name: "ServiceMac",
    aliases: ["MyServiceMac", "First American ServiceMac"],
    assistUrl: "https://myservicemac.com/Home/FinancialAssistance",
    phone: "844-478-2622",
    phoneType: "general",
    hours: null,
    onlineApp: true,
    options: ["Forbearance", "Loan modification", "Payment deferral", "Reinstatement", "Short sale", "Deed in lieu of foreclosure"],
    parent: "First American Financial Corporation",
    subservicer: true,
    note: "ServiceMac is a subservicer for lenders such as Lakeview and Rate. Log in to the Loan Portal and use the Loan Solution Center to apply.",
    verifiedFrom: "https://myservicemac.com/Home/FinancialAssistance",
  },
  {
    slug: "citadel-servicing",
    name: "Citadel Servicing Corporation",
    aliases: ["Citadel Servicing", "Acra Lending"],
    assistUrl: "https://citadelservicing.com/contact-us/",
    phone: "888-800-7661",
    phoneType: "general",
    hours: "Mon-Fri 8am-5pm",
    onlineApp: null,
    options: [],
    note: "Citadel services non-prime loans originated through Acra Lending.",
    verifiedFrom: "https://citadelservicing.com/contact-us/",
  },
];

export const SERVICER_DATA_VERIFIED = 'September 30, 2026';
export const SERVICER_DATA_VERIFIED_ISO = '2026-09-30';

export function getServicer(slug: string): Servicer | undefined {
  return SERVICERS.find((s) => s.slug === slug);
}

/** "800-555-1234" -> "tel:+18005551234" */
export function telHref(phone: string): string {
  return `tel:+1${phone.replace(/\D/g, '').slice(-10)}`;
}

/** Plain-English label for the main number. */
export function phoneLabelFor(s: Servicer): string {
  if (s.phoneLabel) return s.phoneLabel;
  if (s.phoneType === 'loss-mitigation') return 'Published for mortgage assistance';
  return 'Main servicing line: ask for loss mitigation or mortgage assistance';
}
